"""
Cash Flow KPI function library - RECONSTRUCTED.

This file was originally a pure function library used by engine.py (the
Sprint 2 Ratio Engine). It was accidentally overwritten during Sprint 5
Day 31 work with a full pipeline script of the same filename, which broke
engine.py's imports. This is a reconstruction based on:
  - The exact call signatures observed in engine.py (argument order/count)
  - This project's own doc (Section 13 KPI Reference, Module 7 spec)
  - The real label vocabulary already observed in the working
    output/capital_allocation.csv (generated by the original function
    before this file was overwritten): Reinvestor, Mixed, Growth Funded
    by Debt, Liquidating Assets, Distress Signal, Unclassified,
    Pre-Revenue, No CF Data.

NOTE: capital_allocation_pattern() below is a best-effort reconstruction
of the sign-pattern -> label mapping. It is NOT used to overwrite any of
the 91 companies already correctly labeled in output/capital_allocation.csv
(Day 32's script explicitly prefers that file's existing labels). It only
determines the label for companies with no prior entry there - in this
project's current state, that is SBIN only. If "Pre-Revenue" or
"Unclassified" edge-case logic differs from the original in ways that
matter later, it is safe to manually correct SBIN's single row in
output/capital_allocation.csv afterward.
"""
from __future__ import annotations
from typing import Optional, Tuple


def free_cash_flow(operating_activity: float, investing_activity: float) -> Optional[float]:
    """
    Free Cash Flow = CFO + CFI.
    """
    if operating_activity is None or investing_activity is None:
        return None
    return round(operating_activity + investing_activity, 2)


def cfo_quality_score(avg_cfo_pat_ratio: float) -> str:
    """
    Labels the 5-year average CFO/PAT ratio per project doc Module 7.1:
      > 1.0  -> High Quality
      0.5-1.0 -> Moderate
      < 0.5  -> Accrual Risk
    """
    if avg_cfo_pat_ratio is None:
        return "Insufficient Data"
    if avg_cfo_pat_ratio > 1.0:
        return "High Quality"
    if avg_cfo_pat_ratio >= 0.5:
        return "Moderate"
    return "Accrual Risk"


def capex_intensity(investing_activity: float, sales: float) -> Tuple[Optional[float], str]:
    """
    CapEx Intensity = abs(investing_activity) / sales * 100.
    Returns (pct, label) tuple - engine.py extracts pct via result[0].
    Labels per project doc Module 7.2:
      < 3%  -> Asset Light
      3-8%  -> Moderate
      > 8%  -> Capital Intensive
    """
    if investing_activity is None or sales is None or sales == 0:
        return (None, "Insufficient Data")
    pct = round(abs(investing_activity) / sales * 100, 2)
    if pct < 3:
        label = "Asset Light"
    elif pct <= 8:
        label = "Moderate"
    else:
        label = "Capital Intensive"
    return (pct, label)


def fcf_conversion_rate(free_cash_flow_cr: float, operating_profit: float) -> Optional[float]:
    """
    FCF Conversion Rate = FCF / Operating Profit * 100.
    Per project doc Module 7.4: >60% efficient, <30% CapEx heavy.
    """
    if free_cash_flow_cr is None or operating_profit is None or operating_profit == 0:
        return None
    return round(free_cash_flow_cr / operating_profit * 100, 2)


def capital_allocation_pattern(
    operating_activity: float,
    investing_activity: float,
    financing_activity: float,
) -> str:
    """
    Classifies the CFO/CFI/CFF sign combination into one of the 8 patterns
    used elsewhere in this project (see output/capital_allocation.csv for
    the authoritative, already-computed labels for 91 companies).

    Sign-pattern mapping (best-effort reconstruction):
      (+, -, -) -> Reinvestor            (healthy: fund growth + pay down debt from ops)
      (+, -, +) -> Growth Funded by Debt (investing while raising external capital)
      (+, +, -) -> Liquidating Assets    (divesting while paying down debt)
      (+, +, +) -> Mixed                 (divesting AND raising capital - ambiguous)
      (-, -, +) -> Distress Signal       (matches project doc's explicit distress
                                           definition: CFO<0 AND CFF>0)
      (-, +, -) -> Unclassified          (burning cash, divesting, paying debt - unusual)
      (-, -, -) -> Unclassified          (burning cash on all fronts - unusual)
      (-, +, +) -> Unclassified          (burning cash, divesting, raising capital)

    Missing-data fallback ("No CF Data") is handled by the caller in
    engine.py, not here - this function is only called when all three
    inputs are already confirmed non-null.
    """
    cfo_sign = "+" if operating_activity >= 0 else "-"
    cfi_sign = "+" if investing_activity >= 0 else "-"
    cff_sign = "+" if financing_activity >= 0 else "-"
    pattern = (cfo_sign, cfi_sign, cff_sign)

    mapping = {
        ("+", "-", "-"): "Reinvestor",
        ("+", "-", "+"): "Growth Funded by Debt",
        ("+", "+", "-"): "Liquidating Assets",
        ("+", "+", "+"): "Mixed",
        ("-", "-", "+"): "Distress Signal",
        ("-", "+", "-"): "Unclassified",
        ("-", "-", "-"): "Unclassified",
        ("-", "+", "+"): "Unclassified",
    }
    return mapping.get(pattern, "Unclassified")
